### ISSUE TITLE
Since Winston 3.3.3, got an error `Cannot find module 'lodash'` at start up

### ISSUE THREAD

**Issue by franckOL** [sramam/winston-cfg#4]

**Comment by franckOL** [comment]
This about lodash.merge issue. Is there any maintainer for the package ?

**Comment by sramam** [comment]
@franckOL, thank you for reporting the issue. 
This package has fallen into disuse and not been actively maintained. 

That said, I'm really glad you find it useful. 
If you'd be willing to submit a PR, I'll gladly merge it. Even make you the package maintainer if you'd like.

**Comment by franckOL** [comment]
Oh yes very usefull

**Comment by franckOL** [comment]
I try tu compile the package but can't. I don't know typescript.
```bash
src/index.ts(75,21): error TS2345: Argument of type 'Config' is not assignable to parameter of type 'LoggerOptions'.
  Types of property 'filters' are incompatible.
    Type 'Fn[]' is not assignable to type 'MetadataFilter[]'.
      Type 'Fn' is not assignable to type 'MetadataFilter'.
        Type 'void' is not assignable to type 'string | { msg: any; meta: any; }'.
```

**Comment by sramam** [comment]
This seems to be a type Issue - either it's a really simple fix, or going to be really painful! :)
Is it possible for you to share a minimal (or any size really) code segment that illustrates the problem?

**Comment by franckOL** [comment]
In fact, just clone the git repo:

Do
```bash
npm install
npm run clean:dist
npm run build:dist
```

Just to see what happen, no modification at all for the moment.

**Comment by sramam** [comment]
@franckOL , I fixed the type issues in [sramam/winston-cfg/tree/issue-4](https://github.com/sramam/winston-cfg/tree/issue-4) , but the tests are still failing. 

Any chance you can take a stab at making them pass? 
I do not have the time to fix this with the urgency that you seem to need.

**Comment by franckOL** [comment]
I try to do something, but I don t know typescript. So..
And i need to upgrade to winston 3.x.x;..

**Comment by sramam** [comment]
The reason this has package has fallen into disuse is that winston 3.x was a significant rewrite and this form of config was not easily compatible. While I was willing to support making this module work if you needed it for legacy reasons, it's best to abandon it and move on...

**Comment by franckOL** [comment]
Thx for your help. do you know a kind of replacement. I appreciate a lot the configuration with `node-config`

**Comment by sramam** [comment]
Not sure this helps, but I eventually went to using "code" to configure winston 3.x.

The allure of data as configuration is very strong to me - so I did look to see if it would be possible to port this to 3.x. 

Given all the micro-modules that winston went with in 3.x, it was difficult to create any data abstraction that would work and have a reasonable assurance of being correct.
