### ISSUE TITLE
Dependency packages are outdated

### ISSUE THREAD

**Issue by viccsjain** [sramam/winston-cfg#6]
The current version has outdated packages. 
Those packages are causing security vulnerabilities.
Please update those packages like parse-git-config.

parse-git-config have newer version available - 3.0.0

**Comment by sramam** [comment]
@viccsjain, thanks for using the repo. Winston 3.0 introduced many changes that make this module redundant. 
Consequenctly, this module has been abandoned. Apologies if this causes you any grief.
